[package]
name = "lifx-mqtt"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "=1.5.0"
color-eyre = "=0.6.2"
config = "=0.13.3"
derive_builder = "=0.12.0"
eyre = "=0.6.8"
futures = "=0.3.28"
palette = { version = "=0.7.3", features = ["serializing"] }
rand = "=0.8.5"
rumqttc = "=0.23.0"
serde = { version = "=1.0.190", features = ["derive"] }
serde_json = "=1.0.107"
serde_path_to_error = "=0.1.14"
tokio = { version = "=1.33.0", features = ["macros", "full"] }

# https://docs.rs/color-eyre/latest/color_eyre/#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3
